import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Providers from "@/redux/Providers";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="layout">
        <Providers>
        <Toaster
       position="top-center"
      reverseOrder={false}
      />
        <Nav />
        {children}
        <Footer />
        </Providers>
      </body>
    </html>
  );
}
